import { PropsWithChildren } from 'react';
import './global.css';
import { ApolloWrapper, AuthProvider } from '@/components/providers';
import { Toaster } from '@/components/ui/sonner';
import { NuqsAdapter } from 'nuqs/adapters/next/app';

export const metadata = {
  title: 'Welcome to example-frontend',
  description: 'Generated by create-nx-workspace',
};

const RootLayout = ({ children }: PropsWithChildren) => {
  return (
    <html lang="en" className="bg-black">
      <body>
        <ApolloWrapper>
          <AuthProvider>
            <NuqsAdapter>
              <div>{children}</div>
            </NuqsAdapter>
            <Toaster />
          </AuthProvider>
        </ApolloWrapper>
      </body>
    </html>
  );
};

export default RootLayout;
