import { PropsWithChildren } from 'react';
import './global.css';
import { ClerkProvider } from '@clerk/nextjs';
import { ClerkIdProvider } from '../components/providers/ClerkIdProvider';
import { ApolloWrapper } from '../components/providers/ApolloWrapper';

export const metadata = {
  title: 'Tinder | 2CD',
  description: 'Generated by create-nx-workspace',
};

const RootLayout = ({ children }: PropsWithChildren) => {
  return (
    <html lang="en">
      <body className="font-sans antialiased ">
        <ClerkProvider>
          <ClerkIdProvider>
            <ApolloWrapper>
              {children}
            </ApolloWrapper>
          </ClerkIdProvider>
        </ClerkProvider>
      </body>
    </html>
  );
};

export default RootLayout;