import { mergeTypeDefs } from '@graphql-tools/merge';
import { typeDefs as CommonTypeDefs } from './common.schema';
import FoodTypeDef from './food.schema';
import CategoryTypeDef from './category.schema';
import UserTypeDef from './user.schema';
import OrderTypeDef from './order.schema';
import walletHistoryTypeDef from './wallet-notification.schema';
import allNotificationTypeDef from './all-notification.schema';
import OtpTypeDef from './otp-schema';
import orderNotificationTypeDef from './order-notification.schema';
export const typeDefs = mergeTypeDefs([FoodTypeDef, CommonTypeDefs, UserTypeDef, CategoryTypeDef, OrderTypeDef, walletHistoryTypeDef, OtpTypeDef, allNotificationTypeDef, orderNotificationTypeDef]);
