import { PropsWithChildren } from 'react';

import { Footer } from '@/components/footer/Footer';
import { Header } from '@/app/user/home/_components/header/Header';

export const metadata = {
  title: 'Welcome to example-frontend',
  description: 'Generated by create-nx-workspace',
};
const UserLayout = ({ children }: PropsWithChildren) => {
  return (
    <div className="max-w-[1334px] m-auto bg-zinc-950 h-screen flex flex-col">
      <Header />
      <div className="flex-1">{children}</div>
      <Footer />
    </div>
  );
};
export default UserLayout;
